[[redirects]]
  from = "https://www.hlconstrucciones.netlify.app"
  to = "https://hlconstrucciones.com:splat"
  status = 404
  force = true

[[redirects]]
  from = "https://hlconstrucciones.netlify.app"
  to = "https://hlconstrucciones.com:splat"
  status = 301
  force = true